image: python:3.6.4

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - pycodestyle .
          - python -m pytest .
